### PR TITLE
[Y360CMS-191] Provide the association description in the API

### PR DESCRIPTION
**Pull request by aleevas**

### CODE REVIEW

**Review by AndreyMaximov — APPROVED** [review]

**Review by bousquet — COMMENTED** [review]
Does the non-html field provide rich text line breaks?  I would prefer if they didn't have the option to leave /n in there.

**Comment by AndreyMaximov** [comment]
@bousquet yes, the non-HTML field provides line breaks. Why'd prefer if they didn't have the option?

Here are examples of how it works:
---
**With line breaks**

image


```
    "descriptionHtml": "<p>This is <strong>Greater Wichita YMCA</strong>.</p>\n<p>The <a href=\"https://ymcawichita.org/\">association</a> that owns the project.</p>\n",
    "description": "This is Greater Wichita YMCA.\r\n\r\nThe association that owns the project.\r\n"
```
---
**Without line breaks**

image

```
    "descriptionHtml": "<p>This is <strong>Greater Wichita YMCA</strong>. The <a href=\"https://ymcawichita.org/\">association</a> that owns the project.</p>\n",
    "description": "This is Greater Wichita YMCA.&nbsp;The association that owns the project.\r\n"
```

**Comment by bousquet** [comment]
@AndreyMaximov We would like to either remove the rich text styling of this field, or if easier, add a new field called `subtitle` that will be a text field (not text area) and provide room for a short sentence without formatting options.  This is going into native and HTML environments and the options for users to provide Rich text or html is going to cause frustration on both the content provider and developer side of the project.

**Review by bousquet — CHANGES_REQUESTED** [review]
We would like to either remove the rich text styling of this field, or if easier, add a new field called `subtitle` that will be a text field (not text area) and provide room for a short sentence without formatting options. This is going into native and HTML environments and the options for users to provide Rich text or html is going to cause frustration on both the content provider and developer side of the project.

**Comment by AndreyMaximov** [comment]
@bousquet we are adding the "subtitle" field. Please review once again

**Review by duozersk — APPROVED** [review]

**Comment by bousquet** [comment]
Looks good. Thanks.

**Review by bousquet — APPROVED** [review]

**Pull request merged**
